[package]
name = "redirect"
version = "0.1.0"
authors = ["Hampton Moore <me@hampton.pw>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
